# Site settings
title: Mario Durántez
description: Personal portfolio of Mario Durántez
# baseurl: "" # the subpath of your site, e.g. /blog
url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: MARIO</br> DURANTEZ
user_description: I want to make videogames.
user_title: GAME DEV
email: mdurantezs@gmail.com
# twitter_username: warbelt
# github_username:  warbelt

# Google-analytics
google-analytics:
  id: "UA-164550461-1"

exclude: ['package.json', 'src' , 'node_modules']

theme: jekyll-theme-midnight